### ISSUE TITLE
Create contact form 

### ISSUE THREAD

**Issue by Sunny-unik** [Sunny-unik/Urlbit#3]
# description

I want to add a contact form on the /contact route. That form contains two fields a title input, a description text box (has markdown support), and a submit button which sends form data on a /contact-us route via post method. The /contact-us route takes the data sent in the mail to a given mail address.

**Comment by arsanyjoseph** [comment]
I would like to contribute to this 
I have few Qs 
- Do you want the controller to capture the req.body and send it via a mail service (such as nodemailer) to a recipient ? 
- Should I add an extra package to handle markdown support for description field ?

**Comment by Sunny-unik** [comment]
Yes, @arsanyjoseph you are totally correct I want to send mail to my email address through any mailing service (such as nodemailer). I appreciate your willingness to contribute let me know if you want to make any contribution to this task and you are free to add secured packages for this task.

**Comment by Sunny-unik** [comment]
Now, the mail service and basic markdown feature are working fine. Still needs to improve styles, layouts, and add third-party MDX editor instead of textarea element.

**Comment by arsanyjoseph** [comment]
@Sunny-unik Can you point out the improvements you want to make for styles ?

**Comment by Sunny-unik** [comment]
@arsanyjoseph things need to do: 
- update colors
- use font-mono where that looks good
- for styles you can take inspiration from this -> [contact form example](https://herotofu.com/solutions/forms-library/tailwind/simple-contact-form)
- form width can be increased
- add markdown editor 

> Note: If anyone wants to work on these tasks let me know, I will assign this issue to you and you can directly raise PR from your branch to sunny-unik/master branch.

**Comment by arsanyjoseph** [comment]
@Sunny-unik I cannot found a server side markdown editor 
do you have recommendation ? 
I adjusted the style of contact form 
You can re check it

**Comment by Sunny-unik** [comment]
Hi @arsanyjoseph,

Regarding your question about a server-side markdown editor, you actually don't need one for this particular form. Instead, I recommend implementing a client-side markdown editor for the description field. My suggestion is to use [SimpleMDE](https://simplemde.com/), which is easy to integrate and provides a seamless markdown editing experience for users.

You can add the markdown editor by running JavaScript on the DOMContentLoaded event. Here's a sample code snippet:

```html
<!-- Include SimpleMDE CSS via CDN -->
<link rel="stylesheet" href="https://cdn.jsdelivr.net/simplemde/latest/simplemde.min.css">

<!-- Include SimpleMDE JavaScript via CDN -->
<script src="https://cdn.jsdelivr.net/simplemde/latest/simplemde.min.js"></script>

<script>
    document.addEventListener('DOMContentLoaded', function () {
        // Initialize SimpleMDE for the description field
        var simplemde = new SimpleMDE({
            element: document.getElementById('description'),
            forceSync: true, // This option ensures that the markdown content is immediately synced with the textarea
             toolbar: [
                    "bold", "italic", "strikethrough", "|",
                    "heading-1", "heading-2", "heading-3", "|",
                    "code", "quote", "unordered-list", "ordered-list", "|",
                    "link", "image", "table", "|",
                    "preview", "side-by-side", "fullscreen"
                ],
        });
    });
</script>
```

And, I haven't received a pull request regarding the contact form style update. If you could make the changes and raise a pull request, I'll be sure to review and merge it into the `master` branch of Sunny-unik/Urlbit repository.

Thank you for your collaboration!
